### ISSUE TITLE
Change API to avoid having to declaring model repeatedly

### ISSUE THREAD

**Issue by ScottyFillups** [ScottyFillups/key-controller#22]
Consider:

```js
const virtuals = (obj1, obj2, e) => ({
  next () {
    obj1.foo()
  },
  bar: {
    keyup () {
      obj2.bar()
    },
    keydown () {
      obj1.eee(e)
    }
  }
})

export default virtuals
```

If a virtual is a function rather than an object containing `keyup` and/or `keydown`, then it's assumed that the function should be applied on `keydown` (a shorthand). Multiple models will be allowed, and the keyboard `event` will be passed as the last parameter.

**Comment by ScottyFillups** [comment]
@Sokojoe this is going to create a breaking change, thoughts on API changes? Dunno if you're using this

**Comment by Sokojoe** [comment]
@ScottyFillups Nope no issues, go ahead. :+1:
